### ISSUE TITLE
I hope you won't have to resort to the CPU cost of serving ads

### ISSUE THREAD

**Issue by yuhong** [StractOrg/stract#132]
"Well, currently we don't. We are bootstraped and trying to keep costs low. In the future we will have, clearly labelled, contextual ads based on your current search query and a subscription option without ads. Just to re-iterate; we will only use your current search to match ads and will never track you across searches."
I hope you won't have to resort to the CPU cost of serving ads.

**Comment by mikkeldenker** [comment]
Yea this is a very tough problem. I will try to provide some insights behind the thought process on the monetization here.

Some people might be priviliged enough to be able to afford to pay for search, but for a lot of people this might not be the case. If we assume that an open search engine is a good thing for the user, it would be very unfortunate if only those who are privileged enough to have the means to pay for search can get the benefits. This is simply not fair in my opinion.

Other people might actually in practice have the means to pay for search, but since it is something they are used to getting for free, they would prefer not to. Someone else might be tired of seeing ads in their search results and instead wants to pay. All of this is totally fine. The entire mission of Stract is to give users back control over how *they* want to access the internet.

It's true that an ad based business model might create misaligned incentives for a search engine. Even Page and Brin wrote about it in their [Google paper](http://infolab.stanford.edu/pub/papers/google.pdf) (appendix A). This is exactly one of the core reasons why Stract is open source. If we ever start serving results that are not in the best interest of the user, someone will simply take our code and start a competitor. That's why we will never do that.

Another approach would be to sustain it solely with donations. While this is clearly the best option from the users perspective, there unfortunately is a very real cost to develop and provide a viable web scale search engine. It would create a very real risk of Stract suddenly disappearing and I don't think it's sustainable long term. I would love to be proven wrong here, and there are indeed awesome projects that more or less tries this approach (see [marginalia](https://github.com/MarginaliaSearch/MarginaliaSearch) or [mwmbl](https://github.com/mwmbl/mwmbl)).

I hope this provides some insights behind the reasoning. I'll close this issue as there is no action for us to take, but I would very much want to hear if there is a more fair business model that can still ensure that Stract stays sustainable long term.

**Comment by yuhong** [comment]
What I am also talking about however is the CPU power involved in serving ads too.

**Comment by yuhong** [comment]
Also I assume you are much cheaper to run than Google servers, right?
